### ISSUE TITLE
What you are doing is amazing!!! Keep going!!!

### ISSUE THREAD

**Issue by bhurghundii** [cooljeanius/Pyramid#1]
I don't know if you remember me but I am Burgundy - I used to mess around with a bunch of y'all when I was 15/16 online and I was nostalgic so I went to look around for this and I came across your account. I am so happy to see that you've got into FOSS and you actually are contributing too!! Thank you!!

**Comment by cooljeanius** [comment]
> I don't know if you remember me but I am Burgundy - I used to mess around with a bunch of y'all when I was 15/16 online 

...uh... sorry, but I can't say I remember you... can you say where online specifically?

> I am so happy to see that you've got into FOSS and you actually are contributing too!! Thank you!!

...ok, you're welcome?
